/* RUNMATE all-selected-photo collage generator */
(function(){
function loadImage(src){return new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=no;i.src=src})}
function cover(ctx,img,x,y,w,h){const s=Math.max(w/img.width,h/img.height),sw=w/s,sh=h/s,sx=(img.width-sw)/2,sy=(img.height-sh)/2;ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h)}
function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.clip()}
function getSources(){try{return (window.photos||photos||[]).slice(0,10).map(p=>typeof p==='string'?p:(p.data||p.src||p.url)).filter(Boolean)}catch(e){return[]}}
function text(ctx,str,x,y,maxW){if(!str)return;ctx.save();ctx.font='italic 700 42px system-ui,sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';ctx.lineWidth=8;ctx.strokeStyle='rgba(0,0,0,.58)';ctx.fillStyle='#fff';const words=str.trim().split(/\s+/),lines=[];let line='';for(const w of words){const t=line?line+' '+w:w;if(ctx.measureText(t).width>maxW&&line){lines.push(line);line=w}else line=t}if(line)lines.push(line);lines.slice(0,3).forEach((l,i)=>{const yy=y+i*52;ctx.strokeText(l,x,yy);ctx.fillText(l,x,yy)});ctx.restore()}
async function makeCollage(e){if(e){e.preventDefault();e.stopImmediatePropagation()}const srcs=getSources();if(!srcs.length)return note('사진을 먼저 선택해주세요.');let imgs=[];try{imgs=await Promise.all(srcs.map(loadImage))}catch(err){return note('선택한 사진을 불러오지 못했습니다.')}const c=document.getElementById('canvas');if(!c)return;c.width=1080;c.height=1350;const ctx=c.getContext('2d');ctx.fillStyle='#0b1118';ctx.fillRect(0,0,c.width,c.height);const n=imgs.length,pad=24,gap=12,top=96,bottom=250,areaH=c.height-top-bottom,cols=n===1?1:n<=4?2:n<=6?2:3,rows=Math.ceil(n/cols),cellW=(c.width-pad*2-gap*(cols-1))/cols,cellH=(areaH-gap*(rows-1))/rows;imgs.forEach((img,i)=>{const col=i%cols,row=Math.floor(i/cols),x=pad+col*(cellW+gap),y=top+row*(cellH+gap);ctx.save();roundRect(ctx,x,y,cellW,cellH,22);cover(ctx,img,x,y,cellW,cellH);ctx.restore()});const grad=ctx.createLinearGradient(0,c.height-330,0,c.height);grad.addColorStop(0,'rgba(0,0,0,0)');grad.addColorStop(.35,'rgba(0,0,0,.58)');grad.addColorStop(1,'rgba(0,0,0,.9)');ctx.fillStyle=grad;ctx.fillRect(0,c.height-360,c.width,360);ctx.fillStyle='#fff';ctx.font='900 42px system-ui,sans-serif';ctx.textAlign='left';ctx.fillText('RUNMATE',48,62);let km='0.00',time='00:00',pace='--/km';try{const rec=JSON.parse(localStorage.getItem('runs')||'[]').slice(-1)[0]||{};km=Number(rec.km||rec.distance||0).toFixed(2);time=rec.time||rec.elapsedText||time;pace=rec.pace||pace}catch(e){}ctx.font='900 64px system-ui,sans-serif';ctx.fillText(km+' KM',48,1190);ctx.font='700 30px system-ui,sans-serif';ctx.fillText('TIME '+time,50,1244);ctx.textAlign='right';ctx.fillText('PACE '+pace,1030,1244);const cap=document.getElementById('photoText')?.value||'';text(ctx,cap,540,1050,920);ctx.textAlign='left';ctx.font='600 25px system-ui,sans-serif';ctx.fillStyle='rgba(255,255,255,.9)';ctx.fillText(new Date().toLocaleDateString('ko-KR'),50,1300);c.style.display='block';note(srcs.length+'장의 사진을 하나의 인증이미지로 만들었습니다.')}
function note(t){const s=document.getElementById('rmShareStatus');if(s){s.textContent=t;s.classList.add('show');setTimeout(()=>s.classList.remove('show'),3200)}}
function init(){const card=document.querySelector('#share .card');if(!card)return;const old=[...card.querySelectorAll('button')].find(b=>b.textContent.includes('인증 이미지'));if(!old)return;const fresh=old.cloneNode(true);fresh.removeAttribute('onclick');old.replaceWith(fresh);fresh.addEventListener('click',makeCollage,{capture:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,180));else setTimeout(init,180);})();