/* RUNMATE single-page tight collage v4 - elegant handwritten caption */
(function(){
function loadImage(src){return new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=no;i.src=src})}
function cover(ctx,img,x,y,w,h){const s=Math.max(w/img.width,h/img.height),sw=w/s,sh=h/s,sx=(img.width-sw)/2,sy=(img.height-sh)/2;ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h)}
function getSources(){let out=[];try{const arr=typeof photos!=='undefined'?photos:(window.photos||[]);out=Array.from(arr||[]).slice(0,10).map(p=>typeof p==='string'?p:(p?.data||p?.src||p?.url)).filter(Boolean)}catch(e){}if(!out.length){const box=document.getElementById('photos');if(box)out=[...box.querySelectorAll('img')].map(i=>i.src).filter(Boolean).slice(0,10)}return out}
function caption(ctx,str){if(!str)return;ctx.save();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='italic 500 48px "Nanum Pen Script","Nanum Brush Script","Segoe Print","Bradley Hand",cursive';ctx.shadowColor='rgba(0,0,0,.9)';ctx.shadowBlur=14;ctx.shadowOffsetY=3;ctx.lineWidth=3;ctx.strokeStyle='rgba(0,0,0,.48)';ctx.fillStyle='#fff';const words=str.trim().split(/\s+/),lines=[];let line='';for(const w of words){const t=line?line+' '+w:w;if(ctx.measureText(t).width>880&&line){lines.push(line);line=w}else line=t}if(line)lines.push(line);lines.slice(0,2).forEach((l,i)=>{const y=1060+i*58;ctx.strokeText(l,540,y);ctx.fillText(l,540,y)});ctx.restore()}
async function make(e){if(e){e.preventDefault();e.stopImmediatePropagation();e.stopPropagation()}const srcs=getSources();if(!srcs.length)return note('선택된 사진을 찾지 못했습니다. 사진을 다시 선택해주세요.');let imgs;try{imgs=await Promise.all(srcs.map(loadImage))}catch(err){return note('사진을 불러오지 못했습니다.')}const c=document.getElementById('canvas');if(!c)return;c.width=1080;c.height=1350;const ctx=c.getContext('2d');ctx.fillStyle='#080d12';ctx.fillRect(0,0,1080,1350);const n=imgs.length,pad=8,gap=5,top=62,bottom=190,areaH=1350-top-bottom,cols=n===1?1:n<=6?2:3,rows=Math.ceil(n/cols),cw=(1080-pad*2-gap*(cols-1))/cols,ch=(areaH-gap*(rows-1))/rows;imgs.forEach((img,i)=>{const col=i%cols,row=Math.floor(i/cols),x=pad+col*(cw+gap),y=top+row*(ch+gap);ctx.save();ctx.beginPath();ctx.roundRect(x,y,cw,ch,10);ctx.clip();cover(ctx,img,x,y,cw,ch);ctx.restore()});ctx.fillStyle='rgba(0,0,0,.48)';ctx.fillRect(0,0,1080,62);ctx.fillStyle='#fff';ctx.font='900 34px system-ui,sans-serif';ctx.textAlign='left';ctx.fillText('RUNMATE',22,43);const grad=ctx.createLinearGradient(0,1000,0,1350);grad.addColorStop(0,'rgba(0,0,0,0)');grad.addColorStop(.42,'rgba(0,0,0,.62)');grad.addColorStop(1,'rgba(0,0,0,.92)');ctx.fillStyle=grad;ctx.fillRect(0,980,1080,370);caption(ctx,document.getElementById('photoText')?.value||'');let rec={};try{rec=JSON.parse(localStorage.getItem('runs')||'[]').slice(-1)[0]||{}}catch(e){}const km=Number(rec.km||rec.distance||0).toFixed(2),time=rec.time||rec.elapsedText||'00:00',pace=rec.pace||'--/km';ctx.textAlign='left';ctx.fillStyle='#fff';ctx.font='900 54px system-ui,sans-serif';ctx.fillText(km+' KM',24,1215);ctx.font='700 26px system-ui,sans-serif';ctx.fillText('TIME '+time,25,1260);ctx.textAlign='right';ctx.fillText('PACE '+pace,1055,1260);ctx.textAlign='left';ctx.font='600 22px system-ui,sans-serif';ctx.fillStyle='rgba(255,255,255,.88)';ctx.fillText(new Date().toLocaleDateString('ko-KR'),25,1310);c.style.display='block';note(n+'장 모두 한 페이지에 배치했습니다.')}
function note(t){const s=document.getElementById('rmShareStatus');if(s){s.textContent=t;s.classList.add('show');clearTimeout(window.rmColTimer);window.rmColTimer=setTimeout(()=>s.classList.remove('show'),3200)}}
function init(){const card=document.querySelector('#share .card');if(!card)return;const old=[...card.querySelectorAll('button')].find(b=>b.textContent.includes('인증 이미지'));if(!old)return;const fresh=old.cloneNode(true);fresh.removeAttribute('onclick');old.replaceWith(fresh);fresh.addEventListener('click',make,{capture:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,350));else setTimeout(init,350);})();