/* RUNMATE share UX v1 */
(function(){
const css=document.createElement('style');css.textContent=`
#share .card{padding:16px!important}#share .shareHead{display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}.shareTitle{font-size:21px;font-weight:900}.shareCount{font-size:13px;color:#9aa5af;background:#10161b;padding:6px 10px;border-radius:999px}.sharePick{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-bottom:12px}.sharePick button{min-height:52px}.shareGuide{font-size:12px;color:#9aa5af;margin:4px 0 12px;line-height:1.5}.shareActions{display:grid!important;grid-template-columns:1fr 1fr;gap:9px}.shareActions button{min-height:54px}.instaBtn{background:linear-gradient(135deg,#833ab4,#fd1d1d,#fcb045)!important;color:#fff!important}.makeBtn{background:#2d7dff!important;color:#fff!important}.shareStatus{display:none;margin:10px 0;padding:10px 12px;border-radius:12px;background:rgba(45,125,255,.15);color:#b9d7ff;font-size:12px}.shareStatus.show{display:block}#runPhoto{display:none!important}#shareHint{margin:8px 0 12px!important}#share .photos:empty{display:none}.canvas[style*="display: block"],.canvas[style*="display:block"]{margin-bottom:12px}
`;document.head.appendChild(css);
function init(){const page=document.getElementById('share');if(!page)return;const card=page.querySelector('.card');if(!card||document.getElementById('rmShareHead'))return;
 const star=card.querySelector('div[style*="font-size:30px"]');if(star)star.style.display='none';const count=card.querySelector('.count');if(count)count.style.display='none';
 const head=document.createElement('div');head.id='rmShareHead';head.className='shareHead';head.innerHTML='<div class="shareTitle">★ 러닝 인증샷</div><div class="shareCount"><span id="rmCount">0</span> / 10</div>';card.insertBefore(head,card.firstChild);
 const input=document.getElementById('runPhoto');const picks=document.createElement('div');picks.className='sharePick';picks.innerHTML='<button type="button" class="secondary" id="rmPick">📷 사진 선택</button><button type="button" class="secondary" id="rmClear">전체 삭제</button>';input.parentNode.insertBefore(picks,input);const guide=document.createElement('div');guide.className='shareGuide';guide.textContent='사진을 고른 뒤 인증 이미지를 만들면 저장하거나 Instagram으로 공유할 수 있습니다.';picks.after(guide);
 const make=[...card.querySelectorAll('button')].find(b=>b.textContent.includes('인증 이미지'));if(make){make.classList.add('makeBtn');make.textContent='✨ 인증 이미지 만들기'}
 const row=[...card.querySelectorAll('.row')].find(r=>r.textContent.includes('이미지 저장')&&r.textContent.includes('공유'));if(row){row.classList.add('shareActions');const bs=row.querySelectorAll('button');if(bs[0])bs[0].textContent='⬇ 이미지 저장';if(bs[1]){bs[1].textContent='Instagram 공유';bs[1].classList.add('instaBtn')}}
 const status=document.createElement('div');status.id='rmShareStatus';status.className='shareStatus';if(row)row.before(status);
 document.getElementById('rmPick').onclick=()=>input.click();document.getElementById('rmClear').onclick=()=>{if(window.photos)window.photos=[];else try{photos=[]}catch(e){};const box=document.getElementById('photos');if(box)box.innerHTML='';input.value='';sync();const c=document.getElementById('canvas');if(c)c.style.display='none';setStatus('사진을 모두 삭제했습니다.')};input.addEventListener('change',()=>setTimeout(sync,50));sync();
 // Replace only the share button behavior. No repeated alert when image is missing.
 if(row&&row.querySelectorAll('button')[1])row.querySelectorAll('button')[1].onclick=instagramShare;
}
function sync(){const n=document.getElementById('photoCount');const x=document.getElementById('rmCount');if(x)x.textContent=n?n.textContent:'0'}
function setStatus(t){const s=document.getElementById('rmShareStatus');if(!s)return;s.textContent=t;s.classList.add('show');setTimeout(()=>s.classList.remove('show'),2600)}
function canvasFile(){return new Promise(resolve=>{const c=document.getElementById('canvas');if(!c||c.style.display==='none')return resolve(null);c.toBlob(b=>resolve(b?new File([b],'runmate-instagram.jpg',{type:'image/jpeg'}):null),'image/jpeg',.94)})}
async function instagramShare(e){if(e){e.preventDefault();e.stopPropagation()}const count=+(document.getElementById('photoCount')?.textContent||0);if(!count){setStatus('먼저 사진을 선택해주세요.');document.getElementById('rmPick')?.click();return false}let f=await canvasFile();if(!f){setStatus('인증 이미지를 먼저 만들고 다시 눌러주세요.');document.querySelector('.makeBtn')?.scrollIntoView({behavior:'smooth',block:'center'});return false}try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[f]}))){await navigator.share({files:[f],title:'RUNMATE',text:'오늘의 러닝 기록'});setStatus('공유창에서 Instagram을 선택해주세요.')}else{setStatus('이 브라우저는 이미지 공유를 지원하지 않습니다. 이미지 저장 후 Instagram에서 올려주세요.')}}catch(err){if(err&&err.name!=='AbortError')setStatus('공유를 열지 못했습니다. 이미지 저장 후 Instagram에서 올려주세요.')}return false}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();